/**
 * @file bemf_zc.h
 * @brief Digital BEMF zero-crossing detection using ATA6847 comparators.
 *
 * The ATA6847 has built-in BEMF comparators (GDUCR1.BEMFEN=1) that
 * output digital signals on GPIO pins:
 *   RC6 = Phase A BEMF comparator
 *   RC7 = Phase B BEMF comparator
 *   RD10 = Phase C BEMF comparator
 *
 * These outputs go high when the floating phase voltage crosses the
 * virtual neutral point (internally generated by ATA6847).
 */

#ifndef BEMF_ZC_H
#define BEMF_ZC_H

#include <stdint.h>
#include <stdbool.h>
#include "../garuda_types.h"

void BEMF_ZC_Init(volatile GARUDA_DATA_T *pData);
void BEMF_ZC_OnCommutation(volatile GARUDA_DATA_T *pData);
bool BEMF_ZC_Poll(volatile GARUDA_DATA_T *pData);
ZC_TIMEOUT_RESULT_T BEMF_ZC_CheckTimeout(volatile GARUDA_DATA_T *pData);
void BEMF_ZC_ScheduleCommutation(volatile GARUDA_DATA_T *pData);

#if FEATURE_IC_ZC
/**
 * @brief Handle an IC capture event from an SCCP ISR.
 * Implements the post-blanking guard state machine.
 * @param pData ESC runtime data
 * @param channel Which SCCP fired: 0=A, 1=B, 2=C
 * @param captureTick Raw SCCP timer capture value (640 ns ticks)
 */
void BEMF_ZC_IC_OnCapture(volatile GARUDA_DATA_T *pData,
                           uint8_t channel, uint16_t captureTick);

/**
 * @brief Timer1 tick handler for IC ZC: blanking release and guard confirmation.
 * Called from Timer1 ISR every 50 µs.
 * @return true if ZC was just confirmed (caller should schedule commutation)
 */
bool BEMF_ZC_IC_TimerTick(volatile GARUDA_DATA_T *pData);
#endif

#endif /* BEMF_ZC_H */
