/**
 * @file bemf_zc.h
 * @brief Digital BEMF zero-crossing detection using ATA6847 comparators.
 *
 * The ATA6847 has built-in BEMF comparators (GDUCR1.BEMFEN=1) that
 * output digital signals on GPIO pins:
 *   RC6 = Phase A BEMF comparator
 *   RC7 = Phase B BEMF comparator
 *   RD10 = Phase C BEMF comparator
 *
 * These outputs go high when the floating phase voltage crosses the
 * virtual neutral point (internally generated by ATA6847).
 */

#ifndef BEMF_ZC_H
#define BEMF_ZC_H

#include <stdint.h>
#include <stdbool.h>
#include "../garuda_types.h"

void BEMF_ZC_Init(volatile GARUDA_DATA_T *pData);
void BEMF_ZC_OnCommutation(volatile GARUDA_DATA_T *pData);
bool BEMF_ZC_Poll(volatile GARUDA_DATA_T *pData);
ZC_TIMEOUT_RESULT_T BEMF_ZC_CheckTimeout(volatile GARUDA_DATA_T *pData);
void BEMF_ZC_ScheduleCommutation(volatile GARUDA_DATA_T *pData);

#endif /* BEMF_ZC_H */
