# PyInstaller spec for garuda-gui.exe  (build ON WINDOWS: pyinstaller garuda-gui.spec)
# Entry point gui_launcher.py handles both roles: the GUI, and --broker child.
from PyInstaller.utils.hooks import collect_submodules, collect_data_files

hidden = (collect_submodules("pyqtgraph")
          + collect_submodules("garuda_gsp")
          + collect_submodules("garuda_gui")
          + ["serial", "serial.tools.list_ports", "numpy"])

a = Analysis(
    ["gui_launcher.py"],
    pathex=["."],
    binaries=[],
    datas=collect_data_files("pyqtgraph") + [("assets/garuda.svg", "assets")],
    hiddenimports=hidden,
    excludes=["tkinter", "matplotlib", "scipy", "pandas", "anthropic", "mcp"],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz, a.scripts, a.binaries, a.datas,
    name="garuda-gui",
    console=False,            # windowed app; set True temporarily to debug startup
    icon="assets/garuda.ico", # generated by the build script from garuda.svg
    upx=False,
)
